#!/bin/bash

export WANT_AUTOCONF_2_5=1
export WANT_AUTOMAKE=1.7

set -x

aclocal
libtoolize --force --copy
autoheader
automake --add-missing --copy
autoconf
autopoint                       # for iconv/gettext/config.rpath dependency
#configure --enable-maintainer-mode
